LATAM_COUNTRIES = {
    "argentina",
    "bolivia",
    "brasil",
    "brazil",
    "chile",
    "colombia",
    "costa rica",
    "cuba",
    "ecuador",
    "el salvador",
    "guatemala",
    "guyana",
    "haiti",
    "honduras",
    "jamaica",
    "mexico",
    "méxico",
    "nicaragua",
    "panama",
    "panamá",
    "paraguay",
    "peru",
    "perú",
    "republica dominicana",
    "república dominicana",
    "suriname",
    "trinidad y tobago",
    "uruguay",
    "venezuela",
    "latam",
    "latinoamerica",
    "latinoamérica",
    "latin america",
    "caribe",
    "caribbean",
    "south america",
    "sudamerica",
    "sudamérica",
}

NON_LATAM_MARKERS = {
    "europa",
    "asia",
    "africa",
    "estados unidos",
    "usa",
    "canada",
    "canadá",
    "china",
    "japon",
    "japón",
    "rusia",
    "australia",
}

TOPIC_KEYWORDS = {
    "biodiversidad": ["biodivers", "flora", "fauna", "especies", "ecosistema"],
    "fauna marina": ["marina", "oceano", "océano", "pesca", "costa"],
    "hdi": ["hdi", "idh", "desarrollo humano", "ranking"],
    "cultura": ["cultura", "lengua", "tradicion", "tradición", "patrimonio"],
    "defensa": ["defensa", "fuerzas armadas", "militar", "seguridad"],
}
